// src/ai/flows/generate-event-description.ts
'use server';

/**
 * @fileOverview This file defines a Genkit flow to generate compelling event descriptions for GDG events.
 *
 * - generateEventDescription - A function that uses a GenAI model to create engaging content for GDG events.
 * - GenerateEventDescriptionInput - The input type for the generateEventDescription function.
 * - GenerateEventDescriptionOutput - The return type for the generateEventDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateEventDescriptionInputSchema = z.object({
  title: z.string().describe('The title of the event.'),
  date: z.string().describe('The date and time of the event.'),
  location: z.string().describe('The location of the event.'),
  speakers: z.array(z.string()).describe('A list of speakers for the event.'),
  topic: z.string().describe('The topic of the event.'),
  targetAudience: z.string().describe('The target audience for the event.'),
  keyTakeaways: z.string().describe('The key takeaways from the event.'),
});
export type GenerateEventDescriptionInput = z.infer<typeof GenerateEventDescriptionInputSchema>;

const GenerateEventDescriptionOutputSchema = z.object({
  description: z.string().describe('A compelling event description generated by the AI model.'),
});
export type GenerateEventDescriptionOutput = z.infer<typeof GenerateEventDescriptionOutputSchema>;

export async function generateEventDescription(input: GenerateEventDescriptionInput): Promise<GenerateEventDescriptionOutput> {
  return generateEventDescriptionFlow(input);
}

const generateEventDescriptionPrompt = ai.definePrompt({
  name: 'generateEventDescriptionPrompt',
  input: {schema: GenerateEventDescriptionInputSchema},
  output: {schema: GenerateEventDescriptionOutputSchema},
  prompt: `You are an expert event description writer for Google Developer Groups (GDG) events.
  Your goal is to create engaging and informative descriptions that attract attendees.

  Based on the following information, generate a compelling event description:

  Title: {{{title}}}
  Date and Time: {{{date}}}
  Location: {{{location}}}
  Speakers: {{#each speakers}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
  Topic: {{{topic}}}
  Target Audience: {{{targetAudience}}}
  Key Takeaways: {{{keyTakeaways}}}

  Write a description that is concise, attention-grabbing, and highlights the benefits of attending the event.
`,
});

const generateEventDescriptionFlow = ai.defineFlow(
  {
    name: 'generateEventDescriptionFlow',
    inputSchema: GenerateEventDescriptionInputSchema,
    outputSchema: GenerateEventDescriptionOutputSchema,
  },
  async input => {
    const {output} = await generateEventDescriptionPrompt(input);
    return output!;
  }
);
