// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Summarizes academic resources using a GenAI model.
 *
 * - summarizeAcademicResource - A function that handles the summarization of academic notes.
 * - SummarizeAcademicResourceInput - The input type for the summarizeAcademicResource function.
 * - SummarizeAcademicResourceOutput - The return type for the summarizeAcademicResource function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SummarizeAcademicResourceInputSchema = z.object({
  notes: z.string().describe('The academic notes to summarize.'),
});
export type SummarizeAcademicResourceInput = z.infer<typeof SummarizeAcademicResourceInputSchema>;

const SummarizeAcademicResourceOutputSchema = z.object({
  summary: z.string().describe('The summary of the academic notes.'),
  progress: z.string().describe('Progress of the summarization task.'),
});
export type SummarizeAcademicResourceOutput = z.infer<typeof SummarizeAcademicResourceOutputSchema>;

export async function summarizeAcademicResource(input: SummarizeAcademicResourceInput): Promise<SummarizeAcademicResourceOutput> {
  return summarizeAcademicResourceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'summarizeAcademicResourcePrompt',
  input: {schema: SummarizeAcademicResourceInputSchema},
  output: {schema: SummarizeAcademicResourceOutputSchema},
  prompt: `You are an expert academic summarizer. Please summarize the following notes:

Notes: {{{notes}}}

Summary:`, 
});

const summarizeAcademicResourceFlow = ai.defineFlow(
  {
    name: 'summarizeAcademicResourceFlow',
    inputSchema: SummarizeAcademicResourceInputSchema,
    outputSchema: SummarizeAcademicResourceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return {
      ...output!,
      progress: 'Generated a concise summary of the academic notes.',
    };
  }
);
